# Generated by Django 3.0.5 on 2020-04-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adhaar',
            field=models.CharField(default='123456789012', max_length=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Refuse to answer')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lang',
            field=models.CharField(blank=True, choices=[('HI', 'Hindi'), ('EN', 'English'), ('MR', 'Marathi'), ('RJ', 'Rajasthani')], max_length=50),
        ),
    ]
