# Generated by Django 3.0.5 on 2020-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200426_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('P', 'प्राथमिक विद्यालय'), ('H', 'उच्च विद्यालय'), ('C', 'कॉलेज')], default='कॉलेज', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=40000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.CharField(default='basics', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'पुरुष'), ('F', 'महिला'), ('N', 'कोई वरीयता नहीं')], default='N', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lang',
            field=models.CharField(blank=True, choices=[('HI', 'हिन्दी'), ('EN', 'English')], max_length=50),
        ),
    ]
